### PR TITLE
properly prepend ProvisioningTemplate class with helper

### PR DESCRIPTION
**Pull request by laugmanuel**

### CODE REVIEW

**Comment by laugmanuel** [comment]
fixes https://community.theforeman.org/t/unable-to-open-foreman-settings-error-displayed/38001

Want to have a look @evgeni?

**Comment by evgeni** [comment]
This looks like Ruby. I never understood how Ruby's ClassMethods and prepend and include and everything works.

#yolo?

**Comment by laugmanuel** [comment]
It's at least tested locally and it works. I needed a few tries myself. Prepending class methods is just magic...

**Comment by laugmanuel** [comment]
I'll also add a test for that later before merging..

**Comment by evgeni** [comment]
Can you see if https://github.com/dm-drogeriemarkt/foreman_rescue/pull/29 also solves it?
No idea what's cleaner, poking around `singleton_class` or your `prepended` override.

**Comment by laugmanuel** [comment]
> Can you see if #29 also solves it? No idea what's cleaner, poking around `singleton_class` or your `prepended` override.

Your solution also worked. I simplified it even more and added a test for it. This now looks like a good solution to me.

**Comment by evgeni** [comment]
Interesting. I thought `ClassMethods` would be some magic name…

**Comment by laugmanuel** [comment]
I'll go with this PR as we use the same here in git_templates: https://github.com/dm-drogeriemarkt/foreman_git_templates/blob/master/lib/foreman_git_templates/engine.rb#L34

Tests are passing and fix is verified locally - merging...

**Pull request merged**
